openapi: 3.0.3
info:
  title: CoinRank API
  description: |-
    The CoinRank API is a powerful tool that allows users to rate and evaluate cryptocurrencies using the familiar "upvote" and "downvote" system.
  contact:
    email: support@peterfritz.dev
  license:
    name: MIT
    url: https://github.com/peterfritz/coinrank/blob/main/LICENSE
  version: 1.0.0
externalDocs:
  description: Source
  url: https://github.com/peterfritz/coinrank
servers:
  - url: https://api.coinrank.ptr.red/
  - url: https://localhost:8080/
tags:
  - name: coins
paths:
  /coins:
    get:
      tags:
        - coins
      summary: List all coins
      operationId: listCoins
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Coins'
  /coins/{symbol}/upvote:
    post:
      tags:
        - coins
      summary: Upvote a coin
      operationId: upvoteCoin
      parameters:
        - in: path
          name: symbol
          required: true
          schema:
            type: string
            pattern: '^[A-Z0-9]+$'
          description: The coin's symbol
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                properties:
                  updatedCoin:
                    $ref: '#/components/schemas/Coin'
        '400':
          description: Invalid symbol
          content:
            application/json:
              schema:
                properties:
                  error: 
                    type: string
                    example: Invalid symbol
        '404':
          description: Coin not found
          content:
            application/json:
              schema:
                properties:
                  error: 
                    type: string
                    example: Coin not found
  /coins/{symbol}/downvote:
    post:
      tags:
        - coins
      summary: Downvote a coin
      operationId: downvoteCoin
      parameters:
        - in: path
          name: symbol
          required: true
          schema:
            type: string
            pattern: '^[A-Z0-9]+$'
          description: The coin's symbol
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                properties:
                  updatedCoin:
                    $ref: '#/components/schemas/Coin'
        '400':
          description: Invalid symbol
          content:
            application/json:
              schema:
                properties:
                  error: 
                    type: string
                    example: Invalid symbol
        '404':
          description: Coin not found
          content:
            application/json:
              schema:
                properties:
                  error: 
                    type: string
                    example: Coin not found
components:
  schemas:
    Coin:
      type: object
      properties:
        name:
          type: string
          example: Klever
        symbol:
          type: string
          example: KLV
        upvotes:
          type: number
          example: 1
        downvotes:
          type: number
          example: 0
    Coins:
      type: array
      items:
        $ref: '#/components/schemas/Coin'
